port: 8080
service_name: "tg_webhook"
log_level: info

mongo_queue:
  host: "localhost"
  port: 27017
  database: "local"
  timeout: 5
  pool_size: 10
  collection: insta_queue

sentry:
  dsn: "https://f0ddebc2c3d644f7a21e7cc359123fb9:4a0041c586d94493831ed7a96f8c7384@sentry.io/1252689"
